export const Attribute = {
    MARK_COMMA: ",",
    MARK_UNDER_LINE: "_",
    MARK_MIDDLE_LINE: "-",
    MARK_SLASH: "/",
    MARK_COLON: ":",
    MARK_DOT: ".",
    CARRIAGE_PRICE: "CARRIAGE_PRICE",
    APP_TEST_VERSION: "APP_TEST_VERSION",
    USER_PROTOCOL_URI: "USER_PROTOCOL_URI",
    TEST_USER_PROTOCOL_URI: "TEST_USER_PROTOCOL_URI",
};
