export const InitTable = {
    VILLAGE: "T_VILLAGE",
    PLAN: "T_PLAN",
    CARWASH_REGION_SUPPORT: "T_CARWASH_REGION_SUPPORT",
    CARWASH_SCHEDULE: "T_CARWASH_SCHEDULE",
    CARWASH_SCHEDULE_CONFIG: "T_CARWASH_SCHEDULE_CONFIG",
};
